# Generated by Django 3.2 on 2021-07-19 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('states', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2021, 7, 19))),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('length', models.IntegerField(default=0)),
                ('level', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
                ('splits', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_city', to='Data.city')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('permission', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Race_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('time', models.FloatField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('split', models.FloatField(default=0.0)),
                ('in_run', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('sire', models.CharField(max_length=100)),
                ('dam', models.CharField(max_length=100)),
                ('sp', models.FloatField(default=0.0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_data', to='Data.race')),
            ],
        ),
    ]
