# Generated by Django 3.2 on 2021-07-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_alter_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='city',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='race_data',
            name='race',
            field=models.IntegerField(default=1),
        ),
    ]
