# Generated by Django 3.2 on 2021-07-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20210719_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='race_data',
            old_name='race',
            new_name='race_id',
        ),
    ]
